### ISSUE TITLE
form_complete.js

### ISSUE THREAD

**Issue by paulsonak** [ontoportal/ontoportal_web_ui#20]
Hi there,

I am building a new Django app (using jQuery 3.7.1) and hoping to implement some of the widgets you have available for form_complete and a tree view for ontologies. 

Specifically, I have included in my .html form in the header:
```
<script src="{% static 'common/js/form_complete.js' %}" type="text/javascript"></script>
```

and this is the text input:
```
<div class "row mt-3">
    <div class="col-6">
        <label for="target_disease" class="form-label small">Target Disease</label>
        <input id="target_disease" name="target_disease" class="bp_form_complete-BAO-uri" type="text">
    </div>
</div>
```

The error I get is:
```
Uncaught (in promise) TypeError: jQuery(...).bioportal_autocomplete is not a function
    at HTMLInputElement.<anonymous> (form_complete.js:295:18)
    at Function.each (jquery-3.7.1.min.js:2:3129)
    at e.fn.init.each (jquery-3.7.1.min.js:2:1594)
    at formComplete_setup_functions (form_complete.js:235:46)
    at form_complete.js:100:7
```

It looks like the form_complete.js tries to work with jQuery 1.X and use the 1.X migrate tool which isn't applicable to migrate to jQuery 3.X. 

Is it possible to update the form_complete.js to work with jQuery 3.X?

Thank you!

**Comment by jonquet** [comment]
Hello Amanda, these widgets are not super recent...  are you using them to query BioPortal or another instance of OntoPortal .? Maybe @Bilelkihal or @jvendetti in the team can help you.

**Comment by paulsonak** [comment]
Hi, thanks for looping them in! Yes I’m trying to query bioportal, the BAO ontology. I saw that the form_complete.js was forked directly from ontoportal so I don’t know if either team has an updated version, but it would be great if so!

From: Clement Jonquet ***@***.***>
Date: Friday, September 27, 2024 at 2:42 PM
To: ontoportal/ontoportal_web_ui ***@***.***>
Cc: Paulson, Amanda ***@***.***>, Author ***@***.***>
Subject: Re: [ontoportal/ontoportal_web_ui] form_complete.js (Issue #20)
Hello Amanda, these widgets are not super recent. . . are you using them to query BioPortal or another instance of OntoPortal .? Maybe @Bilelkihal or @jvendetti in the team can help you. — Reply to this email directly, view it on GitHub,
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Hello Amanda, these widgets are not super recent... are you using them to query BioPortal or another instance of OntoPortal .? Maybe @Bilelkihal<https://urldefense.com/v3/__https:/github.com/Bilelkihal__;!!LQC6Cpwp!vYppnbMauQawFAbmITk7uzyevY-SVvyBvIlWpVR6VuwEW0OcTNNX0JuL2r6Pvq97YdIIfVhSLgyaL_eJKvIxvFiYFk75Xw$> or @jvendetti<https://urldefense.com/v3/__https:/github.com/jvendetti__;!!LQC6Cpwp!vYppnbMauQawFAbmITk7uzyevY-SVvyBvIlWpVR6VuwEW0OcTNNX0JuL2r6Pvq97YdIIfVhSLgyaL_eJKvIxvFjR9BOAoQ$> in the team can help you.

**Comment by jonquet** [comment]
Dear @paulsonak 
Sorry for late reply on this. We are not working on the widgets anymore. They might eventually be remove from the UIs. 

An approach discussed is to adopt and send our user to the TS4NFDI widgets here: https://ts4nfdi.github.io/terminology-service-suite/comp/latest/?path=/docs/overview--docs
